services:

  iptables-service:
    build: backend
    container_name: iptables_container
    restart: always
    ports:
      - ${EXPOSED_PORT}:${EXPOSED_PORT}
    volumes:
      - /lib/modules:/lib/modules:ro
      - ./ssh_keys/:/etc/ssh/keys/
      - ./nginx/nginx.conf:/app/nginx.conf:rw
    environment:
      - SSH_PRIVATE_KEY_PATH=/etc/ssh/keys/ctf_proxy_rsa_key
      - EXPOSED_PORT=${EXPOSED_PORT}
    networks:
      ctf_proxy_network:
        ipv4_address: 172.30.0.3
    

  nginx:
    build: "nginx"
    hostname: nginx
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - iptables-service
    restart: unless-stopped
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW

  redis:
    image: redis:7
    networks:
      ctf_proxy_network:
        ipv4_address: 172.30.0.4


networks:
  ctf_proxy_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
